import type { NextPage } from 'next';
import Head from 'next/head';
import {Header, Slider, TopSelling} from '../components/';
import HomeHightlight from '../components/HomeHightlight/HomeHightlight';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section>
          <Slider />
        </section>
        <article className='flex flex-col w-full p-4 lg:p-16 gap-y-2'>
          <HomeHightlight />
        </article>
        <div className='flex w-full justify-center'>
          <hr className='w-1/3' />
        </div>
        <section>
          <TopSelling />
        </section>
      </main>
    </div>
  )
}

export default Home
