import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import HomeHightlight from '../components/HomeHightlight/HomeHightlight';
import Logo from '../components/Logo';
import {
  Footer,
  Header,
  InstaPics,
  SectionTitle,
  Separator,
  Slider,
  TopSelling,
  ScrollToTop
} from '../components/';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section>
          <Slider />
        </section>
        <article className='flex flex-col w-full p-4 lg:p-16 gap-y-2'>
          <HomeHightlight />
        </article>
        <div className='flex w-full justify-center'>
          <hr className='w-1/3' />
        </div>
        <section>
          <TopSelling />
        </section>
      </main>
      <section className='mt-20'>
        <div className='flex w-full flex-col md:flex-row items-center justify-between px-4 md:px-8 mb-4 flex-wrap gap-y-1'>
          <div className='flex items-center justify-center flex-col md:flex-row gap-y-1'>
            <SectionTitle title={<Logo />} className="w-full" responsive/>
            <Separator className='hidden md:inline-block'/>
            <span>NAS REDES SOCIAIS</span>
          </div>
          <div className='flex gap-x-2'>
            <Link href={"#"} >
              <a href="">
                <Image src={"/images/assets/fblogo.png"} alt="" width={32} height={32} layout='fixed' />
              </a>
            </Link>
            <Link href={"#"}>
              <a>
                <Image src={"/images/assets/instalogo.png"} alt="" width={34} height={34} layout='fixed' />
              </a>
            </Link>
          </div>
        </div>
        <div>
          <InstaPics />
        </div>
      </section>
      <ScrollToTop />
      <Footer />
    </div>
  )
}

export default Home
