import type { NextPage } from 'next';
import Head from 'next/head';
import {Header, Slider} from '../components/';
import HomeHightlight from '../components/HomeHightlight/HomeHightlight';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section>
          <Slider />
        </section>
        <article className='flex flex-col w-full p-16 gap-y-2'>
          <HomeHightlight />
        </article>
      </main>
    </div>
  )
}

export default Home
